package com.glf.moduel.preciousmetalReco.model;

import java.util.Date;

public class PreciousmetalReco {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preciousmetal_reco.RECO_ID_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    private Integer recoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preciousmetal_reco.RECO_START_DATE_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    private String recoStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preciousmetal_reco.RECO_END_DATE_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    private String recoEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preciousmetal_reco.RECO_IMG
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    private String recoImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preciousmetal_reco.CREATE_USER_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preciousmetal_reco.CREATE_TIME_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preciousmetal_reco.MODIFY_USER_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    private Integer modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preciousmetal_reco.MODIFY_TIME_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preciousmetal_reco.AUDIT_STATUS_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    private Integer auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preciousmetal_reco.AUDIT_USER_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    private Integer auditUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preciousmetal_reco.AUDIT_TIME_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    private Date auditTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preciousmetal_reco.RECO_ID_
     *
     * @return the value of preciousmetal_reco.RECO_ID_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public Integer getRecoId() {
        return recoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preciousmetal_reco.RECO_ID_
     *
     * @param recoId the value for preciousmetal_reco.RECO_ID_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public void setRecoId(Integer recoId) {
        this.recoId = recoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preciousmetal_reco.RECO_START_DATE_
     *
     * @return the value of preciousmetal_reco.RECO_START_DATE_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public String getRecoStartDate() {
        return recoStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preciousmetal_reco.RECO_START_DATE_
     *
     * @param recoStartDate the value for preciousmetal_reco.RECO_START_DATE_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public void setRecoStartDate(String recoStartDate) {
        this.recoStartDate = recoStartDate == null ? null : recoStartDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preciousmetal_reco.RECO_END_DATE_
     *
     * @return the value of preciousmetal_reco.RECO_END_DATE_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public String getRecoEndDate() {
        return recoEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preciousmetal_reco.RECO_END_DATE_
     *
     * @param recoEndDate the value for preciousmetal_reco.RECO_END_DATE_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public void setRecoEndDate(String recoEndDate) {
        this.recoEndDate = recoEndDate == null ? null : recoEndDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preciousmetal_reco.RECO_IMG
     *
     * @return the value of preciousmetal_reco.RECO_IMG
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public String getRecoImg() {
        return recoImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preciousmetal_reco.RECO_IMG
     *
     * @param recoImg the value for preciousmetal_reco.RECO_IMG
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public void setRecoImg(String recoImg) {
        this.recoImg = recoImg == null ? null : recoImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preciousmetal_reco.CREATE_USER_
     *
     * @return the value of preciousmetal_reco.CREATE_USER_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preciousmetal_reco.CREATE_USER_
     *
     * @param createUser the value for preciousmetal_reco.CREATE_USER_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preciousmetal_reco.CREATE_TIME_
     *
     * @return the value of preciousmetal_reco.CREATE_TIME_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preciousmetal_reco.CREATE_TIME_
     *
     * @param createTime the value for preciousmetal_reco.CREATE_TIME_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preciousmetal_reco.MODIFY_USER_
     *
     * @return the value of preciousmetal_reco.MODIFY_USER_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public Integer getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preciousmetal_reco.MODIFY_USER_
     *
     * @param modifyUser the value for preciousmetal_reco.MODIFY_USER_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public void setModifyUser(Integer modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preciousmetal_reco.MODIFY_TIME_
     *
     * @return the value of preciousmetal_reco.MODIFY_TIME_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preciousmetal_reco.MODIFY_TIME_
     *
     * @param modifyTime the value for preciousmetal_reco.MODIFY_TIME_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preciousmetal_reco.AUDIT_STATUS_
     *
     * @return the value of preciousmetal_reco.AUDIT_STATUS_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preciousmetal_reco.AUDIT_STATUS_
     *
     * @param auditStatus the value for preciousmetal_reco.AUDIT_STATUS_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preciousmetal_reco.AUDIT_USER_
     *
     * @return the value of preciousmetal_reco.AUDIT_USER_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public Integer getAuditUser() {
        return auditUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preciousmetal_reco.AUDIT_USER_
     *
     * @param auditUser the value for preciousmetal_reco.AUDIT_USER_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public void setAuditUser(Integer auditUser) {
        this.auditUser = auditUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preciousmetal_reco.AUDIT_TIME_
     *
     * @return the value of preciousmetal_reco.AUDIT_TIME_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preciousmetal_reco.AUDIT_TIME_
     *
     * @param auditTime the value for preciousmetal_reco.AUDIT_TIME_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }
}