package com.glf.moduel.preciousmetalReco.model;

public class PreciousmetalRecoWithBLOBs extends PreciousmetalReco {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preciousmetal_reco.RECO_INFO_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    private String recoInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preciousmetal_reco.RECO_DESC_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    private String recoDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preciousmetal_reco.RECO_INFO_
     *
     * @return the value of preciousmetal_reco.RECO_INFO_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public String getRecoInfo() {
        return recoInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preciousmetal_reco.RECO_INFO_
     *
     * @param recoInfo the value for preciousmetal_reco.RECO_INFO_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public void setRecoInfo(String recoInfo) {
        this.recoInfo = recoInfo == null ? null : recoInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preciousmetal_reco.RECO_DESC_
     *
     * @return the value of preciousmetal_reco.RECO_DESC_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public String getRecoDesc() {
        return recoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preciousmetal_reco.RECO_DESC_
     *
     * @param recoDesc the value for preciousmetal_reco.RECO_DESC_
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public void setRecoDesc(String recoDesc) {
        this.recoDesc = recoDesc == null ? null : recoDesc.trim();
    }
}