package com.glf.moduel.preciousmetalReco.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PreciousmetalRecoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public PreciousmetalRecoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRecoIdIsNull() {
            addCriterion("RECO_ID_ is null");
            return (Criteria) this;
        }

        public Criteria andRecoIdIsNotNull() {
            addCriterion("RECO_ID_ is not null");
            return (Criteria) this;
        }

        public Criteria andRecoIdEqualTo(Integer value) {
            addCriterion("RECO_ID_ =", value, "recoId");
            return (Criteria) this;
        }

        public Criteria andRecoIdNotEqualTo(Integer value) {
            addCriterion("RECO_ID_ <>", value, "recoId");
            return (Criteria) this;
        }

        public Criteria andRecoIdGreaterThan(Integer value) {
            addCriterion("RECO_ID_ >", value, "recoId");
            return (Criteria) this;
        }

        public Criteria andRecoIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("RECO_ID_ >=", value, "recoId");
            return (Criteria) this;
        }

        public Criteria andRecoIdLessThan(Integer value) {
            addCriterion("RECO_ID_ <", value, "recoId");
            return (Criteria) this;
        }

        public Criteria andRecoIdLessThanOrEqualTo(Integer value) {
            addCriterion("RECO_ID_ <=", value, "recoId");
            return (Criteria) this;
        }

        public Criteria andRecoIdIn(List<Integer> values) {
            addCriterion("RECO_ID_ in", values, "recoId");
            return (Criteria) this;
        }

        public Criteria andRecoIdNotIn(List<Integer> values) {
            addCriterion("RECO_ID_ not in", values, "recoId");
            return (Criteria) this;
        }

        public Criteria andRecoIdBetween(Integer value1, Integer value2) {
            addCriterion("RECO_ID_ between", value1, value2, "recoId");
            return (Criteria) this;
        }

        public Criteria andRecoIdNotBetween(Integer value1, Integer value2) {
            addCriterion("RECO_ID_ not between", value1, value2, "recoId");
            return (Criteria) this;
        }

        public Criteria andRecoStartDateIsNull() {
            addCriterion("RECO_START_DATE_ is null");
            return (Criteria) this;
        }

        public Criteria andRecoStartDateIsNotNull() {
            addCriterion("RECO_START_DATE_ is not null");
            return (Criteria) this;
        }

        public Criteria andRecoStartDateEqualTo(String value) {
            addCriterion("RECO_START_DATE_ =", value, "recoStartDate");
            return (Criteria) this;
        }

        public Criteria andRecoStartDateNotEqualTo(String value) {
            addCriterion("RECO_START_DATE_ <>", value, "recoStartDate");
            return (Criteria) this;
        }

        public Criteria andRecoStartDateGreaterThan(String value) {
            addCriterion("RECO_START_DATE_ >", value, "recoStartDate");
            return (Criteria) this;
        }

        public Criteria andRecoStartDateGreaterThanOrEqualTo(String value) {
            addCriterion("RECO_START_DATE_ >=", value, "recoStartDate");
            return (Criteria) this;
        }

        public Criteria andRecoStartDateLessThan(String value) {
            addCriterion("RECO_START_DATE_ <", value, "recoStartDate");
            return (Criteria) this;
        }

        public Criteria andRecoStartDateLessThanOrEqualTo(String value) {
            addCriterion("RECO_START_DATE_ <=", value, "recoStartDate");
            return (Criteria) this;
        }

        public Criteria andRecoStartDateLike(String value) {
            addCriterion("RECO_START_DATE_ like", value, "recoStartDate");
            return (Criteria) this;
        }

        public Criteria andRecoStartDateNotLike(String value) {
            addCriterion("RECO_START_DATE_ not like", value, "recoStartDate");
            return (Criteria) this;
        }

        public Criteria andRecoStartDateIn(List<String> values) {
            addCriterion("RECO_START_DATE_ in", values, "recoStartDate");
            return (Criteria) this;
        }

        public Criteria andRecoStartDateNotIn(List<String> values) {
            addCriterion("RECO_START_DATE_ not in", values, "recoStartDate");
            return (Criteria) this;
        }

        public Criteria andRecoStartDateBetween(String value1, String value2) {
            addCriterion("RECO_START_DATE_ between", value1, value2, "recoStartDate");
            return (Criteria) this;
        }

        public Criteria andRecoStartDateNotBetween(String value1, String value2) {
            addCriterion("RECO_START_DATE_ not between", value1, value2, "recoStartDate");
            return (Criteria) this;
        }

        public Criteria andRecoEndDateIsNull() {
            addCriterion("RECO_END_DATE_ is null");
            return (Criteria) this;
        }

        public Criteria andRecoEndDateIsNotNull() {
            addCriterion("RECO_END_DATE_ is not null");
            return (Criteria) this;
        }

        public Criteria andRecoEndDateEqualTo(String value) {
            addCriterion("RECO_END_DATE_ =", value, "recoEndDate");
            return (Criteria) this;
        }

        public Criteria andRecoEndDateNotEqualTo(String value) {
            addCriterion("RECO_END_DATE_ <>", value, "recoEndDate");
            return (Criteria) this;
        }

        public Criteria andRecoEndDateGreaterThan(String value) {
            addCriterion("RECO_END_DATE_ >", value, "recoEndDate");
            return (Criteria) this;
        }

        public Criteria andRecoEndDateGreaterThanOrEqualTo(String value) {
            addCriterion("RECO_END_DATE_ >=", value, "recoEndDate");
            return (Criteria) this;
        }

        public Criteria andRecoEndDateLessThan(String value) {
            addCriterion("RECO_END_DATE_ <", value, "recoEndDate");
            return (Criteria) this;
        }

        public Criteria andRecoEndDateLessThanOrEqualTo(String value) {
            addCriterion("RECO_END_DATE_ <=", value, "recoEndDate");
            return (Criteria) this;
        }

        public Criteria andRecoEndDateLike(String value) {
            addCriterion("RECO_END_DATE_ like", value, "recoEndDate");
            return (Criteria) this;
        }

        public Criteria andRecoEndDateNotLike(String value) {
            addCriterion("RECO_END_DATE_ not like", value, "recoEndDate");
            return (Criteria) this;
        }

        public Criteria andRecoEndDateIn(List<String> values) {
            addCriterion("RECO_END_DATE_ in", values, "recoEndDate");
            return (Criteria) this;
        }

        public Criteria andRecoEndDateNotIn(List<String> values) {
            addCriterion("RECO_END_DATE_ not in", values, "recoEndDate");
            return (Criteria) this;
        }

        public Criteria andRecoEndDateBetween(String value1, String value2) {
            addCriterion("RECO_END_DATE_ between", value1, value2, "recoEndDate");
            return (Criteria) this;
        }

        public Criteria andRecoEndDateNotBetween(String value1, String value2) {
            addCriterion("RECO_END_DATE_ not between", value1, value2, "recoEndDate");
            return (Criteria) this;
        }

        public Criteria andRecoImgIsNull() {
            addCriterion("RECO_IMG is null");
            return (Criteria) this;
        }

        public Criteria andRecoImgIsNotNull() {
            addCriterion("RECO_IMG is not null");
            return (Criteria) this;
        }

        public Criteria andRecoImgEqualTo(String value) {
            addCriterion("RECO_IMG =", value, "recoImg");
            return (Criteria) this;
        }

        public Criteria andRecoImgNotEqualTo(String value) {
            addCriterion("RECO_IMG <>", value, "recoImg");
            return (Criteria) this;
        }

        public Criteria andRecoImgGreaterThan(String value) {
            addCriterion("RECO_IMG >", value, "recoImg");
            return (Criteria) this;
        }

        public Criteria andRecoImgGreaterThanOrEqualTo(String value) {
            addCriterion("RECO_IMG >=", value, "recoImg");
            return (Criteria) this;
        }

        public Criteria andRecoImgLessThan(String value) {
            addCriterion("RECO_IMG <", value, "recoImg");
            return (Criteria) this;
        }

        public Criteria andRecoImgLessThanOrEqualTo(String value) {
            addCriterion("RECO_IMG <=", value, "recoImg");
            return (Criteria) this;
        }

        public Criteria andRecoImgLike(String value) {
            addCriterion("RECO_IMG like", value, "recoImg");
            return (Criteria) this;
        }

        public Criteria andRecoImgNotLike(String value) {
            addCriterion("RECO_IMG not like", value, "recoImg");
            return (Criteria) this;
        }

        public Criteria andRecoImgIn(List<String> values) {
            addCriterion("RECO_IMG in", values, "recoImg");
            return (Criteria) this;
        }

        public Criteria andRecoImgNotIn(List<String> values) {
            addCriterion("RECO_IMG not in", values, "recoImg");
            return (Criteria) this;
        }

        public Criteria andRecoImgBetween(String value1, String value2) {
            addCriterion("RECO_IMG between", value1, value2, "recoImg");
            return (Criteria) this;
        }

        public Criteria andRecoImgNotBetween(String value1, String value2) {
            addCriterion("RECO_IMG not between", value1, value2, "recoImg");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER_ is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER_ is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(Integer value) {
            addCriterion("CREATE_USER_ =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(Integer value) {
            addCriterion("CREATE_USER_ <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(Integer value) {
            addCriterion("CREATE_USER_ >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("CREATE_USER_ >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(Integer value) {
            addCriterion("CREATE_USER_ <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(Integer value) {
            addCriterion("CREATE_USER_ <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<Integer> values) {
            addCriterion("CREATE_USER_ in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<Integer> values) {
            addCriterion("CREATE_USER_ not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(Integer value1, Integer value2) {
            addCriterion("CREATE_USER_ between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("CREATE_USER_ not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME_ is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME_ is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME_ =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME_ <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME_ >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME_ >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME_ <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME_ <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME_ in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME_ not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME_ between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME_ not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNull() {
            addCriterion("MODIFY_USER_ is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNotNull() {
            addCriterion("MODIFY_USER_ is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserEqualTo(Integer value) {
            addCriterion("MODIFY_USER_ =", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotEqualTo(Integer value) {
            addCriterion("MODIFY_USER_ <>", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThan(Integer value) {
            addCriterion("MODIFY_USER_ >", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("MODIFY_USER_ >=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThan(Integer value) {
            addCriterion("MODIFY_USER_ <", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThanOrEqualTo(Integer value) {
            addCriterion("MODIFY_USER_ <=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIn(List<Integer> values) {
            addCriterion("MODIFY_USER_ in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotIn(List<Integer> values) {
            addCriterion("MODIFY_USER_ not in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserBetween(Integer value1, Integer value2) {
            addCriterion("MODIFY_USER_ between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotBetween(Integer value1, Integer value2) {
            addCriterion("MODIFY_USER_ not between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("MODIFY_TIME_ is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("MODIFY_TIME_ is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("MODIFY_TIME_ =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("MODIFY_TIME_ <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("MODIFY_TIME_ >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME_ >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("MODIFY_TIME_ <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME_ <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("MODIFY_TIME_ in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("MODIFY_TIME_ not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME_ between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME_ not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNull() {
            addCriterion("AUDIT_STATUS_ is null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNotNull() {
            addCriterion("AUDIT_STATUS_ is not null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusEqualTo(Integer value) {
            addCriterion("AUDIT_STATUS_ =", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotEqualTo(Integer value) {
            addCriterion("AUDIT_STATUS_ <>", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThan(Integer value) {
            addCriterion("AUDIT_STATUS_ >", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("AUDIT_STATUS_ >=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThan(Integer value) {
            addCriterion("AUDIT_STATUS_ <", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThanOrEqualTo(Integer value) {
            addCriterion("AUDIT_STATUS_ <=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIn(List<Integer> values) {
            addCriterion("AUDIT_STATUS_ in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotIn(List<Integer> values) {
            addCriterion("AUDIT_STATUS_ not in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusBetween(Integer value1, Integer value2) {
            addCriterion("AUDIT_STATUS_ between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("AUDIT_STATUS_ not between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditUserIsNull() {
            addCriterion("AUDIT_USER_ is null");
            return (Criteria) this;
        }

        public Criteria andAuditUserIsNotNull() {
            addCriterion("AUDIT_USER_ is not null");
            return (Criteria) this;
        }

        public Criteria andAuditUserEqualTo(Integer value) {
            addCriterion("AUDIT_USER_ =", value, "auditUser");
            return (Criteria) this;
        }

        public Criteria andAuditUserNotEqualTo(Integer value) {
            addCriterion("AUDIT_USER_ <>", value, "auditUser");
            return (Criteria) this;
        }

        public Criteria andAuditUserGreaterThan(Integer value) {
            addCriterion("AUDIT_USER_ >", value, "auditUser");
            return (Criteria) this;
        }

        public Criteria andAuditUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("AUDIT_USER_ >=", value, "auditUser");
            return (Criteria) this;
        }

        public Criteria andAuditUserLessThan(Integer value) {
            addCriterion("AUDIT_USER_ <", value, "auditUser");
            return (Criteria) this;
        }

        public Criteria andAuditUserLessThanOrEqualTo(Integer value) {
            addCriterion("AUDIT_USER_ <=", value, "auditUser");
            return (Criteria) this;
        }

        public Criteria andAuditUserIn(List<Integer> values) {
            addCriterion("AUDIT_USER_ in", values, "auditUser");
            return (Criteria) this;
        }

        public Criteria andAuditUserNotIn(List<Integer> values) {
            addCriterion("AUDIT_USER_ not in", values, "auditUser");
            return (Criteria) this;
        }

        public Criteria andAuditUserBetween(Integer value1, Integer value2) {
            addCriterion("AUDIT_USER_ between", value1, value2, "auditUser");
            return (Criteria) this;
        }

        public Criteria andAuditUserNotBetween(Integer value1, Integer value2) {
            addCriterion("AUDIT_USER_ not between", value1, value2, "auditUser");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNull() {
            addCriterion("AUDIT_TIME_ is null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNotNull() {
            addCriterion("AUDIT_TIME_ is not null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeEqualTo(Date value) {
            addCriterion("AUDIT_TIME_ =", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotEqualTo(Date value) {
            addCriterion("AUDIT_TIME_ <>", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThan(Date value) {
            addCriterion("AUDIT_TIME_ >", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("AUDIT_TIME_ >=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThan(Date value) {
            addCriterion("AUDIT_TIME_ <", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThanOrEqualTo(Date value) {
            addCriterion("AUDIT_TIME_ <=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIn(List<Date> values) {
            addCriterion("AUDIT_TIME_ in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotIn(List<Date> values) {
            addCriterion("AUDIT_TIME_ not in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeBetween(Date value1, Date value2) {
            addCriterion("AUDIT_TIME_ between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotBetween(Date value1, Date value2) {
            addCriterion("AUDIT_TIME_ not between", value1, value2, "auditTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 27 11:16:41 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}