package com.glf.moduel.preciousmetalReco.dao;

import com.glf.moduel.preciousmetalReco.model.PreciousmetalReco;
import com.glf.moduel.preciousmetalReco.model.PreciousmetalRecoExample;
import com.glf.moduel.preciousmetalReco.model.PreciousmetalRecoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PreciousmetalRecoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    int countByExample(PreciousmetalRecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    int deleteByExample(PreciousmetalRecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    int deleteByPrimaryKey(Integer recoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    int insert(PreciousmetalRecoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    int insertSelective(PreciousmetalRecoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    List<PreciousmetalRecoWithBLOBs> selectByExampleWithBLOBs(PreciousmetalRecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    List<PreciousmetalReco> selectByExample(PreciousmetalRecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    PreciousmetalRecoWithBLOBs selectByPrimaryKey(Integer recoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") PreciousmetalRecoWithBLOBs record, @Param("example") PreciousmetalRecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") PreciousmetalRecoWithBLOBs record, @Param("example") PreciousmetalRecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    int updateByExample(@Param("record") PreciousmetalReco record, @Param("example") PreciousmetalRecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    int updateByPrimaryKeySelective(PreciousmetalRecoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(PreciousmetalRecoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preciousmetal_reco
     *
     * @mbggenerated Thu Dec 27 11:16:41 CST 2018
     */
    int updateByPrimaryKey(PreciousmetalReco record);
}